# BungeeCord configuration file

listeners:
  - query_port: 25577
    motd: 'Welcome to the BungeeCord Network!'
    host: 0.0.0.0:25565
    max_players: 200
    tab_list: GLOBAL_PING
    forced_hosts:
      survival.example.com: survival   # Forced routing for the survival world
      minigames.example.com: minigames # Forced routing for the minigames world
      lobby.example.com: lobby         # Forced routing for the lobby world
    bind_local_address: true
    ping_passthrough: false
    priority: lobby, survival, minigames  # Define world priority (lobby is first)
    default_server: lobby  # Default "world" players will join (lobby world)
    connect_timeout: 5000
    socket_timeout: 30000
    proxy_protocol: false

worlds:
  lobby:
    address: localhost:25565   # Port for the lobby world (could be the same server or different)
    motd: "Lobby World Server"
    restricted: false
    max_players: 100
    online_mode: false  # Enable online mode for this world
    allow-epk: true
    world_directory: "worlds/lobby" # Define the directory where the world files are located
    
  survival:
    address: localhost:25566  # Port for the survival world
    motd: "Survival World Server"
    restricted: false
    max_players: 100
    online_mode: false
    allow-epk: true
    world_directory: "worlds/survival"  # Define the directory where the survival world files are located

  minigames:
    address: localhost:25567  # Port for the minigames world
    motd: "Minigames World Server"
    restricted: false
    max_players: 50
    online_mode: false
    allow-epk: true
    world_directory: "worlds/minigames"  # Define the directory for the minigames world

ip_forward: true
online_mode: false
prevent_proxy_connections: false

# Connection settings
connection_throttle: 4000

# Permissions and Admins (using LuckPerms or similar)
permissions:
  default:
    - bungeecord.command.server
    - bungeecord.command.list
    - bungeecord.command.send
    - bungeecord.command.alert
    - bungeecord.command.stop
    - bungeecord.command.reload
    - bungeecord.command.disconnect
    - bungeecord.command.shutdown

  admin:
    permissions:
      - bungeecord.command.server
      - bungeecord.command.list
      - bungeecord.command.send
      - bungeecord.command.alert
      - bungeecord.command.stop
      - bungeecord.command.reload
      - bungeecord.command.disconnect
      - bungeecord.command.shutdown
      - minecraft.command.kick
      - minecraft.command.ban
      - minecraft.command.tp
      - minecraft.command.time
      - minecraft.command.gamemode
      - minecraft.command.give
    inheritance: []
    options:
      prefix: '&4[Admin]&f'

# Admins with full permissions can use the following commands
admins:
  - uuid-of-admin-1
  - uuid-of-admin-2

# Optional: World aliases for easier management
aliases:
  kick: kickplayer
  stop: shutdown

# Additional configuration for world management
log_commands: true  # Log all commands run in the console

# Use this section to customize custom messages or other proxy-wide settings
messages:
  no_permission: '&cYou do not have permission to execute this command.'
  player_not_found: '&cPlayer not found on the network.'
  server_not_found: '&cWorld not found on the network.'
  connection_error: '&cThere was an error connecting to the world.'

# Network-wide settings
disabled_commands:
  - disabledcommand1
  - disabledcommand2

# Player pinging settings
ping_passthrough: true
