# BungeeCord configuration file

listeners:
  - query_port: 25577
    motd: 'Welcome to the BungeeCord Network!'
    host: 0.0.0.0:25565
    max_players: 200
    tab_list: GLOBAL_PING
    forced_hosts:
      survival.example.com: survival   # Routing for the survival world
      minigames.example.com: minigames # Routing for the minigames world
      lobby.example.com: lobby         # Routing for the lobby world
    bind_local_address: true
    ping_passthrough: false
    priority: lobby, survival, minigames  # Priority order for connecting servers
    default_server: lobby  # Default server when players join is lobby
    connect_timeout: 5000
    socket_timeout: 30000
    proxy_protocol: false

servers:
  lobby:
    address: localhost:25568   # Port for the lobby server
    motd: "Lobby World Server"  # Message of the day for lobby
    restricted: false
    max_players: 100
    online_mode: false  # Use online mode for this server

  survival:
    address: localhost:25566  # Port for the survival server
    motd: "Survival World Server"
    restricted: false
    max_players: 100
    online_mode: false  # Use online mode for this server

  minigames:
    address: localhost:25567  # Port for the minigames server
    motd: "Minigames World Server"
    restricted: false
    max_players: 50
    online_mode: false  # Use online mode for this server

ip_forward: true
online_mode: true
prevent_proxy_connections: false

# Connection settings
connection_throttle: 4000

# Permissions and Admins (using LuckPerms or similar)
permissions:
  default:
    - bungeecord.command.server
    - bungeecord.command.list
    - bungeecord.command.send
    - bungeecord.command.alert
    - bungeecord.command.stop
    - bungeecord.command.reload
    - bungeecord.command.disconnect
    - bungeecord.command.shutdown

  admin:
    permissions:
      - bungeecord.command.server
      - bungeecord.command.list
      - bungeecord.command.send
      - bungeecord.command.alert
      - bungeecord.command.stop
      - bungeecord.command.reload
      - bungeecord.command.disconnect
      - bungeecord.command.shutdown
      - minecraft.command.kick
      - minecraft.command.ban
      - minecraft.command.tp
      - minecraft.command.time
      - minecraft.command.gamemode
      - minecraft.command.give
    inheritance: []
    options:
      prefix: '&4[Admin]&f'

# Admins with full permissions can use the following commands
admins:
  - uuid-of-admin-1
  - uuid-of-admin-2

# Optional: Server aliases for easier management
aliases:
  kick: kickplayer
  stop: shutdown

# Additional configuration for server management
log_commands: true  # Log all commands run in the console

# Use this section to customize custom messages or other proxy-wide settings
messages:
  no_permission: '&cYou do not have permission to execute this command.'
  player_not_found: '&cPlayer not found on the network.'
  server_not_found: '&cServer not found on the network.'
  connection_error: '&cThere was an error connecting to the server.'

# Network-wide settings
disabled_commands:
  - disabledcommand1
  - disabledcommand2

# Player pinging settings
ping_passthrough: true
